In [1]:
import tensorflow as tf

In [2]:
a=tf.constant(2.0,tf.float32)

In [3]:
a

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [4]:
b=tf.constant(3.0)

In [5]:
b

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [6]:
c=tf.constant(6)

In [7]:
c


<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [8]:
W=tf.Variable([.3],dtype=tf.float32)
b=tf.Variable([-.3],dtype=tf.float32)

In [9]:
# A session is run to evaluate the node and this is called the Tensorflow runtime

In [10]:
a=tf.constant(5.0)
b=tf.constant(3.0)

In [11]:
c=a*b

In [12]:
# Launch the graph in a session.
sess = tf.compat.v1.Session()

In [13]:
print(c)

tf.Tensor(15.0, shape=(), dtype=float32)
